### ISSUE TITLE
Add ability to disable symlink deletion in docker

### ISSUE THREAD

**Issue by idanlah** [sureshfizzy/CineSync#31]
In docker version, is it possible to add an .env param to control whether to enable or disable symlink removal?
the issue is that sometimes the rclone container is unavailable or hasn't started yet so cinesync thinks the files were removed and keeps deleting everything. 

if you think another solution for this issue is more appropriate or better please share

**Comment by sureshfizzy** [comment]
Instead of disabling removals, how about adding some variables like RCLONE_MOUNT= true

If enabled, it will check for the mounted directories and if it is unmounted, it will wait for it to come online untill further actions are taken. It's just an idea, feel free to add yours I'll check on them.

**Comment by idanlah** [comment]
@sureshfizzy sure, your idea is better but I don't think the script is aware of which implementation is used for the directories, its not aware of any rclone.
So how can the script check if a directory is actually mounted or not just empty with no movies or shows?
I once thought of just checking if there is a version.txt in the root folder but it's very specific to zurg and zurg can change the structure anytime.

lmk what you think

**Comment by sureshfizzy** [comment]
Rclone is currently far away from the script as this script is standalone. I need to make another specific script to check for the rclone directory mount or improve the polling monitor to specially verify if it is enabled.

Also to confirm if it is the actually mounted directory or not, as you said we can pass a simple version.txt inside that mount folder.

**Comment by sureshfizzy** [comment]
@idanlah New improvements for rclone-specific functions have been pushed, you can test them. By default, the variables are false, and only set to true if it is a rclone-mounted directory.

**Comment by idanlah** [comment]
thank you very much!, but i don't think this code will work if rclone is an external docker container because there is not rclone process inside the CineSync container.
i don't think CineSync container is aware of any rclone as i said in my previous comment. 
for example, in my setup i have rclone_zurg container and cinesync container and i just bind my rclone path using volume bind meaning that rclone_zurg binds /zurg to my host and cinecsync binds /zurg from host to cineSync container.

`    if os.getenv('RCLONE_MOUNT', 'false').lower() == 'true':
        try:
            result = subprocess.run(
                ['ps', 'aux'],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                # Look for a specific rclone mount process related to this path
                rclone_found = False
                for line in result.stdout.split('\n'):
                    if 'rclone' in line and 'mount' in line and path in line:
                        rclone_found = True
                        if mount_state is not True:
                            log_message(f"Found rclone mount point at: {path}", level="INFO")
                        return True, path

                if not rclone_found:
                    log_message(f"Path {path} is a mount point but no rclone process found for it", level="DEBUG")
                    return False, None`

**Comment by sureshfizzy** [comment]
I made this in a different workaround, basically when you enable it to true, it just counts the entire source directory as a rclone mount even if it is a local directory. This has been done intentionally to avoid docker issues as you said.

**Comment by idanlah** [comment]
@sureshfizzy thanks ill check, can you also point me to where this workaround is the code?

**Comment by sureshfizzy** [comment]
> @sureshfizzy thanks ill check, can you also point me to where this workaround is the code?

https://github.com/sureshfizzy/CineSync/blob/main/MediaHub/monitor/polling_monitor.py#L77

Since this condition is too broad when we set RCLONE_MOUNT to true it is ideally considering local directories as rclone even if the directory is not related to rclone. It is better to turn off the Condition when not needed.

**Comment by idanlah** [comment]
@sureshfizzy i still don't understand:
`if 'rclone' in line and 'mount' in line and path in line`

in my case in docker, it will never find any rclone process in `result = subprocess.run` (because my rclone is running as a different container)  so it will never find "rclone" and "mount" in the result and it will never enter this 'if' statement.
so it will never return True and will wait indefinitely for the mount.

what am i missing?

**Comment by sureshfizzy** [comment]
> @sureshfizzy i still don't understand: `if 'rclone' in line and 'mount' in line and path in line`
> 
> in my case in docker, it will never find any rclone process in `result = subprocess.run` (because my rclone is running as a different container) so it will never find "rclone" and "mount" in the result and it will never enter this 'if' statement. so it will never return True and will wait indefinitely for the mount.
> 
> what am i missing?

The point is it never finds rclone process :) it is just a variable check based on RCLONE_MOUNT, others are just for failsafe if things get worse

for eg: let's take a directory

/home/user/mount -- if rclone_mount is set to true it treats as mount directory, if it is false it will be treated as non mount directory

**Comment by idanlah** [comment]
sure, i got:

```
2024-11-17 16:53:31 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'

2024-11-17 16:53:31 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies

2024-11-17 16:53:31 [INFO] Waiting for mount directory to become available...

2024-11-17 16:53:41 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'

2024-11-17 16:53:51 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
```

**Comment by sureshfizzy** [comment]
> sure, i got:
> 
> ```
> 2024-11-17 16:53:31 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
> 
> 2024-11-17 16:53:31 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies
> 
> 2024-11-17 16:53:31 [INFO] Waiting for mount directory to become available...
> 
> 2024-11-17 16:53:41 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
> 
> 2024-11-17 16:53:51 [ERROR] Error checking rclone process: [Errno 2] No such file or directory: 'ps'
> ```

Ok, i guess alpine docker doesn't recognise ps command, can you run which ps to check if it is able to find one ?

If not try installing it.

apt install procps

**Comment by idanlah** [comment]
@sureshfizzy installed procps and rclone. now getting:

```
2024-11-17 17:10:00 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies

2024-11-17 17:10:00 [INFO] Waiting for mount directory to become available...
```

as i thought, because it can't find any rclone mount INSIDE the cinesync container. rclone mount is not done inside cinesync container.
it will only work on regular host setup

**Comment by sureshfizzy** [comment]
> @sureshfizzy installed procps and rclone. now getting:
> 
> ```
> 2024-11-17 17:10:00 [WARNING] Mount unavailable - Directory is not mounted: /zurg/movies
> 
> 2024-11-17 17:10:00 [INFO] Waiting for mount directory to become available...
> ```
> 
> as i thought, because it can't find any rclone mount INSIDE the cinesync container. rclone mount is not done inside cinesync container. it will only work on regular host setup

I'm sure I'm missing something coz when I tested it, it does work without issues on docker. I'll check this tomorrow morning and drop a fix soon. Also can you let me know your setup so that I can have the same setup on mine and test it

**Comment by idanlah** [comment]
when you tested it did you install rclone inside the cinesync docker container?

here is my setup:
```
  rclone_zurg:
    image: rclone/rclone
    container_name: rclone_zurg
    restart: unless-stopped
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - $USERDIR/zurg:/data:rshared 
      - $DOCKERDIR/rclone/config:/config/rclone
      - /etc/passwd:/etc/passwd:rodc 
      - /etc/group:/etc/group:ro
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm.
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://zurg:9999 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    command: "mount zurg: /data --vfs-cache-mode full --allow-other --allow-non-empty --uid=1000 --gid=1000 --umask=002 --dir-cache-time 10s"
```

```
  cinesync:
    image: sureshfizzy/cinesync:latest
    networks:
      - t2_proxy
    tty: true
    command: ["python3", "MediaHub/main.py", "--auto-select"]
    entrypoint: ["/custom_entrypoint.sh"]
    container_name: cinesync
    # restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $USERDIR/zurg/:/zurg  # Mount home directory to provide access to home files
      - $USERDIR/media:/mnt  # Mount /mnt for access to external storage
      - $DOCKERDIR/cinesync/db:/app/db  # Mount local db folder to persist database files
      - $DOCKERDIR/cinesync/.env:/app/.env
      - ./custom_entrypoint/cinesync/custom_entrypoint.sh:/custom_entrypoint.sh  # Adjust the path as necessary
    depends_on:
      rclone_zurg:
        condition: service_healthy
    healthcheck:
      test:  ["CMD", "sh", "-c", "test -f /zurg/version.txt || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
```
