### ISSUE TITLE
Error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Carlosjrlu** [sureshfizzy/CineSync#46]
I think I'm in the correct track for getting CineSync to work, it recognizes the files in my zurg rclone mount and tries to symlink but it gets permission denied. :(
`cinesync  | 2025-01-14 05:54:22 [INFO] File not found in database. Initiating processing for: /mnt/zurg/__all__/[SubsPlease] Honzuki no Gekokujou (01-36) (1080p) [Batch]`
`cinesync  | 2025-01-14 05:54:22 [ERROR] Failed to process file: /mnt/zurg/__all__/[SubsPlease] Honzuki no Gekokujou (01-36) (1080p) [Batch]. Error: [Errno 13] Permission denied: '/home/CineSync'`

**Comment by sureshfizzy** [comment]
are you running using docker ? have you updated the guid and puid in the compose file ?

**Comment by Carlosjrlu** [comment]
I made the output directory for CineSync with correct permissions and now it works. It generates all the symlinks, although plex don't seem to recognize them. (I can see the files when adding new folder to the library but the movies are not added)
Example:
![Screenshot_20250114_122227_Samsung Internet](https://github.com/user-attachments/assets/45779517-b4c7-4856-9ea6-faa40069cb35)

**Comment by sureshfizzy** [comment]
Can you share the compose file for Plex and cinesync

**Comment by Carlosjrlu** [comment]
```yml
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guayaquil
      - VERSION=docker
      - PLEX_CLAIM= #optional
  #    deploy:
  #      resources:
  #        reservations:
  #          devices:
  #            - driver: nvidia
  #              count: 1
  #              capabilities: [gpu]
  #    ports:
  #      - "32400:32400"
    volumes:
      - ./plex/config:/config
      - /mnt:/mnt
    restart: unless-stopped

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:v0.9.3-final
    container_name: zurg
    restart: unless-stopped
    healthcheck:
      test: curl -f localhost:9999/dav/version.txt || exit 1
    ports:
      - 9999:9999
    volumes:
      - ./zurg/config.yml:/app/config.yml
      - ./zurg/data:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      TZ: America/Guayaquil
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/zurg:/data:rshared
      - ./zurg/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --uid=1000 -gid=1000 --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"

  cinesync:
    image: sureshfizzy/cinesync:latest
    container_name: cinesync
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      # - /home:/home  # Mount home directory to provi>
      - /mnt:/mnt  # Mount /mnt for access to external>
      - ./cinesync/db:/app/db  # Mount local db folder>
      - ./cinesync/.env:/app/.env
    depends_on:
      - rclone
```
